name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:

env:
  IMAGE: anjankumar31n/chart-app:${{ github.sha }}   # <‑‑ clearer tag

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE }}

  deploy:
    needs: build-push
    runs-on: ubuntu-latest
    steps:
      - name: Remote deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            IMAGE=${{ env.IMAGE }}
            docker pull $IMAGE
            docker stop chart || true && docker rm chart || true
            docker run -d --restart always --name chart -p 80:5000 $IMAGE
